import type { InvestigationAction } from "../game/model";

/** All authored investigation actions for the first playable chapter. */
export const ACTIONS: readonly InvestigationAction[] = [
  {
    id: "read-case-file",
    minDay: 1,
    maxDay: 2,
    label: "调阅失踪档案",
    location: "总部终端 / CASE-07",
    mode: "archive",
    teaser: "七名失踪者都曾在零点后拨打物业电话。",
    result:
      "七份报案记录的地址栏都被人用红笔改过。原地址各不相同，修改后的地址却全是“槐荫里 7 栋”。最后一通电话没有求救，只有一个男人反复问：我的房间到底是哪一间？",
    evidence: ["ev-disappearance-pattern"],
  },
  {
    id: "inspect-lobby",
    minDay: 1,
    label: "让鬼影进入门厅",
    location: "槐荫里 7 栋 / 一层",
    mode: "field",
    teaser: "封条完好，里面却传来有人搬动木牌的声音。",
    result:
      "鬼影沿封条下方渗入门厅。墙上十六块门牌都比周围墙皮新，旧钉孔则留在完全不同的位置。鬼影试图靠近楼梯时，先于你抬起了头。",
    evidence: ["ev-scratched-plates"],
    shadowCost: 1,
  },
  {
    id: "question-caretaker",
    minDay: 1,
    maxDay: 3,
    label: "询问老门卫周师傅",
    location: "临时安置点",
    mode: "contact",
    teaser: "他坚持封楼以后，每晚仍有人敲值班室的窗。",
    result:
      "周师傅说，失踪前的人都听过三次敲门。第一次没人回应，第二次会有人喊出住户姓名，第三次才有人开门。但他亲眼见过不开门的人照样失踪——敲门并不是全部规律。",
    evidence: ["ev-knock-sequence"],
  },
  {
    id: "compare-register",
    minDay: 2,
    label: "对照物业登记册",
    location: "总部终端 / 扫描档案",
    mode: "archive",
    teaser: "纸张上的住户信息似乎每天都在变化。",
    result:
      "扫描件显示，同一页登记表在三个夜晚出现了不同笔迹。每次变化后，至少一名住户被调到了并不存在的房号。被修改的姓名都出现在次日失踪名单里。",
    evidence: ["ev-register-mismatch"],
    requiresEvidence: ["ev-disappearance-pattern"],
  },
  {
    id: "probe-room-201",
    minDay: 2,
    label: "试探 201 空置房",
    location: "槐荫里 7 栋 / 二层",
    mode: "field",
    teaser: "登记册写着空置，门内却整夜播放电视。",
    result:
      "鬼影穿过门缝。没有通电的电视正在播放一段监控：201 的门牌被摘下，钉到 203 门上。录像结束后，房内才响起敲门声。时间顺序与周师傅的说法相反。",
    evidence: ["ev-plate-moved"],
    shadowCost: 1,
    requiresEvidence: ["ev-scratched-plates"],
  },
  {
    id: "call-resident-xu",
    minDay: 2,
    maxDay: 4,
    label: "接通徐蓉的求救电话",
    location: "未知房间 / 电话线路",
    mode: "contact",
    teaser: "她说自己被困在 202，可档案显示她住在 203。",
    result:
      "徐蓉能说出 203 的家具摆放，却看不见 202 门上的全家福。她身后的墙每隔十分钟传来一次刮擦声，像有人正在把门牌钉到另一侧。",
    evidence: ["ev-false-resident"],
  },
  {
    id: "inspect-room-202",
    minDay: 3,
    label: "确认 202 住户身份",
    location: "槐荫里 7 栋 / 二层",
    mode: "field",
    teaser: "门内的人声称自己是徐蓉，但地上没有她的影子。",
    result:
      "鬼影在床下找到徐蓉的身份证和两把 203 钥匙。门内的人没有影子，仍能准确描述 203 的每件家具。它转向你的鬼影，问了一句：你又住在哪？",
    evidence: ["ev-identity-copy"],
    shadowCost: 1,
    requiresEvidence: ["ev-false-resident"],
  },
  {
    id: "watch-blackout",
    minDay: 3,
    label: "监看零点熄灯",
    location: "槐荫里 7 栋 / 二层楼道",
    mode: "field",
    teaser: "物业线路会在 00:17 准时跳闸十一秒。",
    result:
      "灯灭后，203 房中背对门站立的人皮转向新门牌。灯再亮起，它的脸已经变成原 201 住户。替换发生在熄灯后，目标与当前门牌对应。",
    evidence: ["ev-blackout-replacement"],
    shadowCost: 1,
    requiresEvidence: ["ev-plate-moved"],
  },
  {
    id: "reconstruct-nail-marks",
    minDay: 3,
    label: "重建门牌变更顺序",
    location: "总部终端 / 图像比对",
    mode: "archive",
    teaser: "旧钉孔能还原三晚前的房间分配。",
    result:
      "你把门框旧钉孔、登记册修改时间和失踪顺序叠在一起。所有受害者失踪前，都曾短暂拥有一个与登记身份不一致的房间。敲门只负责让这栋楼注意到他们。",
    evidence: ["ev-identity-chain"],
    requiresEvidence: ["ev-register-mismatch", "ev-plate-moved"],
  },
  {
    id: "answer-third-knock",
    minDay: 4,
    label: "回应第三次敲门",
    location: "槐荫里 7 栋 / 临时安全屋",
    mode: "field",
    teaser: "利用已确认的规律，主动让居民楼登记你的身份。",
    result:
      "第三次敲门响起时，你报出一个不存在的姓名。门外沉默了十一秒，随后一块空白门牌从门缝下滑进来。你的影子在上面留下了自己的轮廓。你取得了临时住户身份。",
    flags: ["temporary-resident"],
    requiresFlags: ["rule-confirmed"],
  },
  {
    id: "recover-old-plate",
    minDay: 4,
    label: "取回 201 旧门牌",
    location: "槐荫里 7 栋 / 垃圾通道",
    mode: "field",
    teaser: "一块不再属于任何房间的旧门牌，可以成为灵异锚点。",
    result:
      "鬼影从垃圾通道深处拖出 201 的旧门牌。木牌背面没有灰尘，只有一行不断变换的住户姓名。你用金箔封住边缘，它暂时停止变化。",
    flags: ["plate-anchor"],
    shadowCost: 1,
    requiresEvidence: ["ev-plate-moved"],
  },
  {
    id: "map-shadow-route",
    minDay: 4,
    label: "标记跨房间影路",
    location: "槐荫里 7 栋 / 阴影夹层",
    mode: "field",
    teaser: "让鬼影寻找门牌变化时唯一不移动的黑暗。",
    result:
      "鬼影连续穿过 201、202 与 203，却没有经过楼道。三间房的阴影在墙后连成一处夹层，那里挂着整栋楼所有被撤下的门牌。你记住了一条能抵达源头的影路。",
    flags: ["shadow-route"],
    shadowCost: 1,
    requiresEvidence: ["ev-blackout-replacement"],
  },
  {
    id: "rescue-xu",
    minDay: 5,
    label: "把徐蓉送回正确房间",
    location: "槐荫里 7 栋 / 二层",
    mode: "field",
    teaser: "在熄灯前调回门牌，验证规律能否被反向利用。",
    result:
      "你把 203 门牌钉回原位，并在熄灯前把真正的徐蓉带入房内。敲门声越过她，落在走廊另一端。她活了下来，也证明规律可以被利用，而不是只能逃避。",
    flags: ["resident-rescued"],
    requiresFlags: ["temporary-resident", "plate-anchor"],
  },
  {
    id: "trace-building-origin",
    minDay: 5,
    label: "追查七栋旧档",
    location: "城建档案馆",
    mode: "archive",
    teaser: "这栋楼最早的住户表里没有房号，只有姓名。",
    result:
      "七栋曾是临时安置楼。四十年前，一场火灾后所有幸存者被重新分房，但登记员在当晚失踪。最初的门牌没有数字，只有住户姓名——门牌鬼分配的从来不是空间，而是身份。",
    evidence: ["ev-building-origin"],
    requiresEvidence: ["ev-identity-chain"],
  },
  {
    id: "stabilize-shadow",
    minDay: 5,
    label: "封存鬼影一昼夜",
    location: "临时安全屋",
    mode: "recovery",
    teaser: "牺牲一次行动，用完全照明压回已经独立的影子。",
    result:
      "你让安全屋所有灯保持开启，坐在四面无影的位置直到天亮。尸斑没有消失，但远处那个先于你行动的影子暂时退回脚下。它记住了这次束缚。",
    flags: ["shadow-stabilized"],
    shadowRecovery: 1,
  },
  {
    id: "seal-stairwell",
    minDay: 6,
    label: "封死楼梯间错误出口",
    location: "槐荫里 7 栋 / 楼梯间",
    mode: "field",
    teaser: "阻止驾驭当晚出现第四个错误房间。",
    result:
      "你用旧门牌和金箔封住楼梯间。墙面随即浮出一个不存在的“204”，又在封条下缓慢褪去。最终行动时，居民楼只剩一条可供重新分配的路径。",
    flags: ["stairwell-sealed"],
    requiresFlags: ["plate-anchor"],
  },
  {
    id: "brief-headquarters",
    minDay: 6,
    label: "向总部提交行动预案",
    location: "加密通讯",
    mode: "contact",
    teaser: "留下规律、影路和失败后的封锁指令。",
    result:
      "总部批准第七日行动。通讯末尾附有一条低权限简报：大昌市负责人杨间刚处理完一起鬼域事件。你没有权限查看细节，只看到一句备注——不要相信灵异空间里的门。",
    flags: ["headquarters-briefed"],
    requiresFlags: ["shadow-route"],
  },
  {
    id: "listen-behind-wall",
    minDay: 6,
    label: "最后一次确认影路",
    location: "槐荫里 7 栋 / 墙后夹层",
    mode: "field",
    teaser: "使用鬼影确认门牌源头仍在，但这可能越过复苏边界。",
    result:
      "鬼影抵达夹层深处。一块没有姓名的门牌正在等待你。你收回能力时，走廊里所有影子都比住户本人早一步转身。路线没有变化，代价却已经无法忽视。",
    evidence: ["ev-blank-plate"],
    shadowCost: 1,
    requiresFlags: ["shadow-route"],
  },
];

/** Human-readable evidence entries shown in the permanent case archive. */
export const EVIDENCE_LABELS: Readonly<Record<string, string>> = {
  "ev-disappearance-pattern": "七名失踪者的地址都被改成槐荫里 7 栋。",
  "ev-scratched-plates": "门牌下方存在与当前位置不一致的旧钉孔。",
  "ev-knock-sequence": "不开门的人也会失踪，敲门不是完整死因。",
  "ev-register-mismatch": "登记册会把住户写入不存在或错误的房号。",
  "ev-plate-moved": "门牌调换发生在敲门之前。",
  "ev-false-resident": "徐蓉自称在 202，却只记得 203 的陈设。",
  "ev-identity-copy": "202 中的替代者拥有记忆，但没有影子。",
  "ev-blackout-replacement": "熄灯后，错误房间会把人替换成对应住户。",
  "ev-identity-chain": "所有受害者失踪前都曾被分配到错误房间。",
  "ev-building-origin": "最初的门牌记录姓名而非房间数字。",
  "ev-blank-plate": "源头处存在一块等待新住户的空白门牌。",
};
